### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Image is not allocated.

### ISSUE THREAD

**Issue by Coraline774477** [MarkusBordihn/BOs-Player-Companions#9] opened 2022-08-10 21:53 UTC
Minecraft: 1.19.1
Forge: 42.0.9
Player Companions: 3.1.0

I was playing for a while till the game crashed due to what the title says above. 
I was bringing my newly tamed wolf pack from a far away land and while on my journey the game decided to crash which it was bound to regardless since something was going on from the start of my play session till the crash.

Here, take a look;

Log: [2022-08-10-1.log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/9304201/2022-08-10-1.log)

Unfortunately there's no crash report even tho the game did crash.

[04:44:16] [Render thread/ERROR]: Can't get entityTexture for literal{Rainy}[style={}] (SUPPRESSED)
[04:44:16] [Render thread/WARN]: java.lang.Throwable: Can't get entityTexture for literal{Rainy}[style={}]

After my fairy Rainy's entityTexture started going bonkers this is what started to go wonky 11 minutes later;

[04:55:43] [Render thread/WARN]: Error getting face image for techbrew: Image is not allocated. NativeImage[RGBA 256x256@0S]
[04:55:44] [Render thread/WARN]: Error getting face image for gdude2002: Image is not allocated. NativeImage[RGBA 64x64@0S]
[04:55:45] [Render thread/ERROR]: ########## GL ERROR ##########
[04:55:45] [Render thread/ERROR]: @ Render
[04:55:45] [Render thread/ERROR]: 65540: Invalid scancode -1
[04:57:01] [Render thread/WARN]: TileDrawStep.updateRegionTexture was slow: 61.9889 (Warning limit reached)
[04:57:01] [Render thread/WARN]: TileDrawStep.updateRegionTexture: Avg:     0.02ms, Min:        0ms, Max:     316.07ms, Total:          3 sec, Count:   206947, Canceled:        0, Slow:       10

Then for the entire time every single player companions entityTecture started going haywire/wonky till the game had enough 4+ hours later...

[15:20:23] [Render thread/ERROR]: GL Error in method: texParameter ERROR: 1285 (SUPPRESSED)
[15:20:23] [Render thread/WARN]: java.lang.Throwable: GL Error in method: texParameter ERROR: 1285
[15:20:23] [Render thread/ERROR]: GL Error in method: enableBlend ERROR: 1285 (SUPPRESSED)
[15:20:23] [Render thread/WARN]: java.lang.Throwable: GL Error in method: enableBlend ERROR: 1285
[15:20:23] [Render thread/ERROR]: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Image is not allocated.

To me this looks like a rendering mod such as Rubidium might be causing this but the thing about this is that I need Rubidium or else I would have to go back to OptiFine which ain't no better and might cause more problems or worse...graphical glitches, rendering errors, problems with my mods list with optifine or even world corruption caused by optifine!...
 
Btw if Rubidium was the cause of this crash then why did all of the entityTextures for the player companions started going bonkers for the entire time till the game ultimately crashed???

**Comment by MarkusBordihn** [comment] 2022-08-11 09:05
Thanks for the report. I don't think that the problem is related to Rubidium or a Shader, because I'm using Rubidium myself. ;)

![image](https://user-images.githubusercontent.com/12183293/184099970-5815b370-8bad-4283-b149-43273556f89c.png)

It looks like more an issue with another mod which tries to display the entities on a screen / map or so, because the crash occurs in "TileDrawStep.updateRegionTexture" which is not used by the mod at all.

Furthermore I implemented a check to make sure a valid texture is returned, like:
https://github.com/MarkusBordihn/BOs-Player-Companions/blob/1.19.1/src/main/java/de/markusbordihn/playercompanions/entity/PlayerCompanionEntityData.java#L357

But I don't see this error message at all, so it's not an issue with this mod itself.

I found some similar error reports which pointing to "journeymap":
- https://github.com/TeamJM/journeymap/issues/489
- https://github.com/TeamJM/journeymap/issues/34

Please try to load your world without "journeymap", to see if the error disappears or if you get other errors instead.

I also recommend to switch to version 1.19.2, because 1.19.1 is considered as deprecated and will no longer supported by most mod authors.

**Comment by mysticdrew** [comment] 2022-08-11 21:31
> * [[1.18.2] Hang on entering a world, may be due to "Can't get entityTexture" TeamJM/journeymap#489](https://github.com/TeamJM/journeymap/issues/489)
> * [[1.10.2] Web map not showing map TeamJM/journeymap#34](https://github.com/TeamJM/journeymap/issues/34)

Those issues are unrelated to the current issue. 

Please create an issue in the Journeymap github issue tracker and/or come to our discord so we can get this resolved.

**Comment by MarkusBordihn** [comment] 2022-08-11 22:05
@Coraline774477 
Please check if you get the same or similar issues without the "journeymap" mod.

- If you don't get the same issues without the "journeymap" mod, please create a issue on the Journeymap github issue tracker and/or come to their discord to discuss this more in detail.

@mysticdrew 
Thanks a lot for the feedback. I only mentioned these issues, because they including the same kind of custom error messages.
Without having access to the "journeymap" source code it's hard to pin point the issue from my side. :/

**Comment by mysticdrew** [comment] 2022-08-11 22:12
> Without having access to the "journeymap" source code it's hard to pin point the issue from my side

I would like to open source it, but I do not have permission. I recently ditched the old awt.BufferedImage code to use the new lwjgl STB_Image which is what minecraft uses. It was a pretty big undertaking, I did some extensive testing, but I cannot test with every mod out there. 

Looking through the log, none of the jourenymap errors should have caused a crash. The GL errors may have caused some odd rendering of things possibly.. With out a crash log, it is really hard to ascertain what caused the crash. There will not be a crash log if it was a JVM crash. 
 
 @Coraline774477 do you happen to have a file in your root minecraft directory that is named something like this?
 `hs_err_pid000.log` the 000 can be any number.

**Comment by Coraline774477** [comment] 2022-08-12 10:39
I thought that the cause was coming from either Rubidium or Player Companions because what I've read in the log I thought it was coming from Player Companions at first then Rubidium cause of the OpenGL error(s) at the end of the log(s) but since I ain't no mod creator nor a coder I don't understand exactly where this issue was originating from since the log wasn't being specific enough and there's no crash report about the crash that had occurred a few days ago...

Apparently that's not the case by most of the information that you've told me and now I'm suspecting Journey Map that's the cause.
I use Journey Map as well as Xaero's Minimap/Worldmap as well but those two mods are glitchy right now which is why I'm using Journey Map or else I would be using Xaero's Minimap/Worldmap mod instead and wouldn't have ran I to this issue in the first place.
But then again I possibly would've ran I to the same issue or a new one would've showed up...

**Comment by Coraline774477** [comment] 2022-08-12 10:46
"I also recommend to switch to version 1.19.2, because 1.19.1 is considered as deprecated and will no longer supported by most mod authors."

Why I'm still on 1.19.1 is cause alot of the mods in my mod lists haven't been updated to 1.19.2 yet or else I would've updated both of my 1.19.1 worlds to 1.19.2 already but in order for me to do that is for both mod lists of both worlds to be updated to 1.19.2.
Which means all of the mods on both mod lists needs to be updated  to 1.19.2 so that I wouldn't have to completely start all over for both worlds (Cora World 1.19.1 and Cora World Guns) cause not all of the mods have been updated to 1.19.2 yet....

**Comment by Coraline774477** [comment] 2022-08-12 11:24
"Coralibe774477 do you happen to have a file in your root minecraft directory that is named something like this?
hs_err_pid000.log the 000 can be any number."

Where can I find my minecraft's root directory exactly? 
Since I've never really experienced this type of crash before but I've experienced crashes that didn't log it via crash report/log which is infuriating since I do want to resolve any issues that occur during my play sessions.

Also I am a Tlauncher user cause mojang's official launcher sucks cause in Task Manager there's multiple background processes that the official launcher "uses" which I believe that if I stop one of those processes that the game could possibly crash which is why I'm still using Tlauncher.
I've been a cracked client/user for years (since 2016 as of minecraft 1.10.2 with what was called TeamExtreame launcher before TeamExtreame server's doors have closed permanently) up till 2020 or so when a friend on discord on a discord server that they and I were apart of gave me a redeem code to officially get minecraft java edition with my Microsoft account which at the time was using one of my alt email addresses till a few months ago when the email address that was associated with my main Microsoft account got hacked (this Github account is my replacement for my original account since that too was associated with the hacked email address as well as my old discord account which I already have a new discord account as a replacement)..

Now my main Microsoft account uses one of my other alt email addresses but not my main email address since I already have a Microsoft account associated with my main email address but why I haven't been using that Microsoft account was cause I used that one for an alt profile for minecraft bedrock edition which the username for that account was TOCoraline774477 meaning The Other Coraline77447 as a reference to The Other Coraline if Coraline 2 was a thing which it ultimately was but ultimately had it's "plug" pulled (meaning that the producers  of the film stopped Coraline 2's production) as of the film production due to many different reasons, one if them possibly being financial...

**Comment by mysticdrew** [comment] 2022-08-12 14:28
> "I also recommend to switch to version 1.19.2, because 1.19.1 is considered as deprecated and will no longer supported by most mod authors."
> 
> Why I'm still on 1.19.1 is cause alot of the mods in my mod lists haven't been updated to 1.19.2 yet or else I would've updated both of my 1.19.1 worlds to 1.19.2 already but in order for me to do that is for both mod lists of both worlds to be updated to 1.19.2. Which means all of the mods on both mod lists needs to be updated to 1.19.2 so that I wouldn't have to completely start all over for both worlds (Cora World 1.19.1 and Cora World Guns) cause not all of the mods have been updated to 1.19.2 yet....

Pretty much all 1.19.1 mods will work with 1.19.2, the changes were very minor. 

> Where can I find my minecraft's root directory exactly?

depends where you installed it, you were able to find the log in the original posting which is in the logs directory of the minecraft root. 

> Also I am a Tlauncher user cause mojang's official launcher

I cannot provide support to tlauncher users.

**Comment by Coraline774477** [comment] 2022-08-13 12:55
"Pretty much all 1.19.1 mods will work with 1.19.2, the changes were very minor."

Ok, I'll need to test that out for myself to find out if both of my mods lists will work in 1.19.2 with the remaining mods still in 1.19.1.
Also how minor were those changes/fixes for any 1.19.1 mods to work or else mods like AttributeFix, Lucent, Architectury would've marked their 1.19.2 versions as compatible with 1.19.1?

Anyways, if most of the mods in both lists don't work then I'll have to wait for those mods to be updated to 1.19.2 exclusively like AttributeFix, Lucent, and Architectury. (AttributeFix and Lucent were recently updated to 1.19.2 but I was using them as examples since both of those mods skipped 1.19/1.19.1 entirely but if they were to have been ported to 1.19 or 1.19.1 and would've tried them out in 1.19.2 those two possibly wouldn't have worked anyways.)

"Also I am a Tlauncher user cause mojang's official launcher sucks"

"I cannot provide support to tlauncher users."

As I've said above that I do have an official copy of the game now but I prefer to continue to use Tlauncher until Mojang actually improves the official launcher and takes away at least twp or three of it's background processes since I always stop unwanted/needed background processes in task manager to free up some RAM (even tho by mid play session most of those background processes will automatically restart themselves..smh, stupid Windows and Microsoft...)

Also since you guys can't provide me support then I guess I can't send vital info about what really happened during that play session and I may end up going back to Xaero's Minimap/Worldmap despite their waypoints being all messed up but at least they're not causing any crashes..yet... (_But I really don't want to go back to Xaero's Minimap/Worldmap since their waypoints are glitchy in 1.19.1+ since I can't see their waypoints at all and they are enabled but just can't see them which means there's a glitch going on in them that's preventing me from using those two mods..._)

BTW sorry about the last bits of my last reply getting a bit too off topic..I was a bit too exited to get started to learn and then make my very first minecraft animation...

**Comment by MarkusBordihn** [comment] 2022-08-14 23:42
First of all let me clarify something, most of the mod authors are very keen to help and to resolve specific issues.
But sometimes is tricky like in this case without any real crash log or debug logs.

The main problem for most of the issues is that we need to be able to reproduce the issue our self in some way.
This is only possible with the standard launcher like Curse Forge or Minecraft directly.
All other launcher behaving completely different and we are not able to install several version of launcher just to reproduce an issue. Furthermore there are some launchers which I would not trust or want to install on my system for other reasons.
For this reason we could only provide support for the official launchers.

> Why do you have so many fairies???

For this mod I have just a test world with several spawner (with companion spawn eggs) for each companion type.
This makes it easy for me to test new variants or to see if there are any performance issues. ;)

> Where can I find my minecraft's root directory exactly?

Normally it's the main folder which includes your "logs", "resources" and "mods" folder.

The file could be named something like `hs_err_pid22388.log` and includes additional debug information.
But not sure if tlauncher is providing such a log file.

![image](https://user-images.githubusercontent.com/12183293/184559050-18cb354f-fc2a-408d-a401-73bcb7ab5c76.png)

If possible you should try to load your world / mod pack with the official launcher to see if you get the same issues.

- If you getting the same issue you should report this issue to Journey Map directly.
- If you are not getting the same issue, then it seems related to the launcher itself and there is not a lot they could do.
- 
I will close this issue now, but feel free to provide additional details directly to  Journey Map, if needed.

**Closed by MarkusBordihn** 2022-08-14 23:42 UTC
Labels: invalid

**Comment by Coraline774477** [comment] 2022-08-15 14:15
"Why do you have so many fairies???"

"For this mod I have just a test world with several spawner (with companion spawn eggs) for each companion type.
This makes it easy for me to test new variants or to see if there are any performance issues. ;)"

I know that you do that for testing purposes but I was a little confused but now I'm curious as to how many different types of companions such as fairies, samurais, corgis, and such during your play sessions? (If you do have any time to just play minecraft with mods as well as your companions that you've created)

Like what I've said that I only want to tame a certain amount of fairies, samurais, corgis, and eventually the new raptors. 
For all of them I would prefer to tame them while they're still babies as I've said above as to why but if I want to I would tame them as adults but only one tho (depending if I find a baby one first then that wouldn't be the case since that to me doesn't make any sense to tame a baby fairy then an adult fairy..)

BTW I'm planning on using ATLauncher instead of TLauncher since I think that what may have happened was possibly just one of those one time rando type crashes that happens when using Tlauncher and I am starting to get annoyed about that as well as making false crash/issue reports such as this one when there's not much info about the crashes like this one that I've "reported".
And I can tell you that Tlauncher does sometimes provide files like (hs_err_pid22388.log) BUT they don't have .log in the name and the last file that was created (without the .log in it's name) was a few days prier to the day that the crash happened..

I know that I should just stick with the official launcher to avoid issues like this but I refuse to use the official launcher as I've said above as to why but at least I'm switching from Tlauncher to ATLauncher or some other launcher since I've been using Tlauncher for a few years now and really do want to change/switch launchers that might be better than both the official launcher and Tlauncher but if these other launchers still causes the same issue then I guess I should just remain on the official launcher.....
