### ISSUE TITLE
Mobs without waiting sound causing crashes.

### ISSUE THREAD

**Issue by M25R4PTOR** [MarkusBordihn/BOs-Player-Companions#29] opened 2023-10-12 13:20 UTC
**Describe the bug**
Crash Game Like https://github.com/MarkusBordihn/BOs-Player-Companions/issues/27 but its rooster, fairy and samurai.
I used version player_companions_1.20.1-6.7.0

**To Reproduce**
1. Open World LAN
2. Rooster friends stay sit
3. Wait and the game crash

**Expected behavior**
No crash xD

**Debugging**
[crash-2023-10-12_15.03.53-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12882823/crash-2023-10-12_15.03.53-server.txt)
[crash-2023-10-12_16.48.28-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12885116/crash-2023-10-12_16.48.28-server.txt)
[crash-2023-10-12_17.29.05-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12885119/crash-2023-10-12_17.29.05-server.txt)

If you can fix it I can test it this Friday/Saturday night

Thanks for everything!

**Comment by MarkusBordihn** [comment] 2023-10-12 17:08
Duplicate of https://github.com/MarkusBordihn/BOs-Player-Companions/issues/28

**Closed as completed by MarkusBordihn** 2023-10-12 17:08 UTC
Labels: bug, duplicate
